openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/danubetech/credential-verifier/0.0.1
info:
  description: This is an open API specification for verifying digital credentials based on standards such as the Verifiable Credentials Data Model (https://www.w3.org/TR/vc-data-model/), JWT (https://tools.ietf.org/html/rfc7519), and Open Badges (https://openbadges.org/). Implementations of this API may differ in terms of which data formats or proof formats they do or do not support. Also, implementations may choose to not support certain parts of this API (e.g. optional parts include retrieving a verification status that has already been created).
  version: "0.0.1"
  title: Credential Verifier API
  contact:
    email: markus@danubetech.com
  license:
    name: All documents in this Repository are licensed by contributors under the [W3C Software and Document License](http://www.w3.org/Consortium/Legal/copyright-software).
tags:
  - name: internal
    description: Internal APIs facing the Verifier.
paths:
  /verifications:
    post:
      tags:
        - internal
      summary: Verifies a credential and returns its verification status.
      operationId: verifyCredential
      description: Verifies a credential and returns its verification status. Support of this part of the API is REQUIRED for implementations.
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: The credential to be verified.
      responses:
        '201':
          description: verification status successfully created!
          content:
            application/json:
              schema:
                type: object
                description: The credential's verification status. This SHOULD include a reference or ID that can be used later for other parts of the API, e.g. retrieving a verification status that has already been created.
        '400':
          description: invalid input!
        '500':
          description: error!
  /verifications/{verificationReference}:
    get:
      tags:
        - internal
      summary: Retrieves a verification status that has already been created, and returns it in the response body.
      operationId: retrieveVerification
      description: Retrieves a verification status that has already been created, and returns it in the response body. The retrieved verification status MUST be identical to the original verification status when it was first created. Support of this part of the API is OPTIONAL for implementations.
      parameters:
        - in: path
          required: true
          name: verificationReference
          schema:
            type: string
          description: Reference to a verification status that has been created.
      responses:
        '200':
          description: verification status successfully retrieved!
          content:
            application/json:
              schema:
                type: object
                description: The retrieved verification status.
        '400':
          description: invalid input!
        '404':
          description: verification status not found!
        '500':
          description: error!
        '501':
          description: not supported by this implementation!
