name: "Lint OpenAPI Yaml Files"

on:
  pull_request:
  workflow_dispatch:

jobs:
  openapi-lint:
    runs-on: ubuntu-latest
    steps:

      # Check out repo, set up node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci

      # Run linter
      - run: npm run lint
